let days = [
    {'day':0,'message':''},
    {'day':1,'message':'Pomyśl dzisiaj o 3 powodach, dzięki którym możesz się uśmiechnąć. Nie czekaj, uśmiechnij się! : )'}, 
    {'day':2,'message':'Znajdź 15 minut na ciszę, stwórz przestrzeń dla siebie samego i dla  Boga.'}, 
    {'day':3,'message':'Pomyśl, kogo w ostatnim czasie powinieneś przeprosić, zrób to.'},
    {'day':4,'message':'Napisz listę 6 rzeczy, które w sobie lubisz. Popatrz na siebie oczyma Tego, który Ciebie stworzył.'},
    {'day':5,'message':'Podziękuj osobom, które kochasz za to, że po prostu są obecna w Twoim życiu.'},
    {'day':6,'message':'Pomyśl, w jaki sposób możesz dzisiaj ubogacić inncyh. Jak możesz sprawić, że ktoś po spotkaniu z tobą poczuje się kochany.'},
    {'day':7,'message':'Znajdź pół godziny na spotkanie z Jezusem w Najświętszym Sakramencie. Niech ten czas będzie wpatrywaniem się w osobę ukochaną. Wykorzystaj go na 100%.'},
    {'day':8,'message':'Napisz do trzech bliskich tobie osób z zapytanim, co w tobie lubią. Odwdzięcz się im tym samym i pokaż im, co ty w nich lubisz.'},
    {'day':9,'message':'Znajdź dziś wieczorem czas na rachunek sumienia. Pomyśl na ile dzisiaj kochałeś Boga, siebie samego i drugiego człowieka.'},
    {'day':10,'message':'Wyjdź dzisiaj na którki spacer. Popatrz na niebo, gwiazdy, księżyc... Postaraj się dostrzec Boga w Jego stworzeniu i podziękuj mu za nie.'},
    {'day':11,'message':'Powiedz dzisiaj 3 bliskim sosobom coś miłego.'},
    {'day':12,'message':'Zrób dzisiaj dla siebie coś miłego'},
    {'day':13,'message':'Włóż dzisiaj 100% w każdą czynność, którą będziesz wykonywał. Popatrz na to z perspektywy życia wiecznego'},
    {'day':14,'message':'Podaruj dzisiaj komuś swój czas.'},
    {'day':15,'message':'Pomyśl dzisiaj o małym, dopiero co narodzonym maluszku. Użyj do tego wyobraźni lub jeśli jest to trudne popatrz na zdjęcia. Zastanów się, w jakim miejscu to dzieciątko czułoby się najlepiej. Czy chciałoby leżeć w brudnym, zagraconym pomieszczeniu? Być może najwyższy czas na posprzątanie w pokoju twojego serca?'},
    {'day':16,'message':'Zastanów się, komu i w jaki sposób możesz dzisiaj pomóc. Pamiętaj, że równie ważna jest pomoc duchowa w postaci modlitwy.'},
    {'day':17,'message':'Odmów dziesiątkę różańca za kobiety spodziewające się dziecka.'},
    {'day':18,'message':'Znajdź w dzisiejszym dniu czas na spotkanie z przyjacielem.'},
    {'day':19,'message':'Podziękuj dzisiaj Bogu za 5 rzeczy w twoim życiu.'},
    {'day':20,'message':'"Pan blisko jest, oczekuj go, Pan blisko jest w nim serca moc." Zastanów się, na co w życiu czekasz, co jest przedmiotem Twoich oczekiwań, kogo lub czego nie możesz się doczekać?'},
    {'day':21,'message':'Zrób dzisiaj i ofiaruj bliskiej osobie coś zrobionego własnoręcznie (być może coś słodkiego).'},
    {'day':22,'message':'Pomyśl dzisiaj o osobach w twoim życiu, które trudno jest ci, pomódl się za nie.'},
    {'day':23,'message':'Postaraj się dziasiaj nie tyle mówić co słychać. Prawdziwie wsłuchaj się w głos Boga i drugiego człowieka.'},
    {'day':24,'message':'Podziękuj dzisiaj towjej mamie za to, że cię urodziła. Pomódl się za nią.'}
];